"""
models.py — Shared data models (dataclasses) used across all pipeline modules.
"""

from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional


@dataclass
class SilenceGap:
    """A detected window of silence safe for narration insertion."""
    start: float          # seconds
    end: float            # seconds
    duration: float       # seconds (end - start)
    gap_id: int = 0       # sequential index

    def usable_duration(self, safety_padding: float) -> float:
        """Available narration time after applying safety padding."""
        return max(0.0, self.duration - 2 * safety_padding)


@dataclass
class SceneDescription:
    """Raw English scene description generated by Gemini Vision."""
    gap_id: int
    english_text: str
    gap: SilenceGap
    frames_used: list[str] = field(default_factory=list)  # paths to extracted frames


@dataclass
class TeluguNarration:
    """Translated & duration-optimized Telugu narration for one gap."""
    gap_id: int
    telugu_text: str
    gap: SilenceGap
    estimated_duration: float = 0.0   # seconds (pre-synthesis estimate)
    optimized: bool = False           # was text shortened to fit?


@dataclass
class TTSClip:
    """A synthesized audio clip ready for mixing."""
    gap_id: int
    audio_path: Path
    actual_duration: float            # seconds (measured after synthesis)
    gap: SilenceGap
    telugu_text: str
    tts_speed: float = 1.0


@dataclass
class PipelineResult:
    """Final output summary returned by the pipeline."""
    input_video: Path
    narration_track: Path             # audio_description_telugu.mp3
    merged_video: Optional[Path]      # movie_with_AD.mp4 (if requested)
    metadata_json: Path               # JSON timeline
    total_gaps_detected: int = 0
    total_gaps_narrated: int = 0
    total_gaps_skipped: int = 0
    processing_time_seconds: float = 0.0
